name: Build and Push to GHCR

on:
  push:
    branches:
      - main
      - dev


permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Semgrep scan (gate)
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/ci
            p/docker
            p/kubernetes
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests


      - name: Normalize image owner
        id: image
        shell: bash
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "owner_lower=$OWNER_LOWER" >> $GITHUB_OUTPUT
          echo "image=ghcr.io/$OWNER_LOWER/other-service" >> $GITHUB_OUTPUT


      - name: Set image tag & DDL_AUTO by branch
        id: config
        shell: bash
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
            echo "DDL_AUTO=update" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "DDL_AUTO=validate" >> $GITHUB_ENV
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local load for Trivy)
        shell: bash
        run: |
          docker buildx build \
            --build-arg DDL_AUTO=${{ env.DDL_AUTO }} \
            -t ${{ steps.image.outputs.image }}:${{ env.IMAGE_TAG }} \
            -t ${{ steps.image.outputs.image }}:${{ github.sha }} \
            --load \
            .

      - name: Trivy image scan (gate HIGH,CRITICAL)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: ${{ steps.image.outputs.image }}:${{ env.IMAGE_TAG }}
          format: table
          vuln-type: os,library
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
        env:
          TRIVY_USERNAME: ${{ github.repository_owner }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
        shell: bash
        run: |
          docker push ${{ steps.image.outputs.image }}:${{ env.IMAGE_TAG }}
          docker push ${{ steps.image.outputs.image }}:${{ github.sha }}


        